# Generated by Django 4.1.7 on 2023-03-27 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='profile_image',
            new_name='user_image',
        ),
    ]
