# Generated by Django 4.1.7 on 2023-04-05 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_alter_article_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=128, unique=True)),
                ('social_media_title', models.CharField(choices=[('FB', 'Facebook'), ('IM', 'Instagram'), ('TT', 'TikTok'), ('TW', 'Twitter'), ('YB', 'Youtube')], max_length=2)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
