# Generated by Django 4.1.7 on 2023-04-05 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_socialmedia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialmedia',
            old_name='author',
            new_name='user',
        ),
    ]
