# Generated by Django 4.1.7 on 2023-04-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_rename_author_socialmedia_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='social_media_title',
            field=models.CharField(choices=[('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('TikTok', 'TikTok'), ('Twitter', 'Twitter'), ('Youtube', 'Youtube')], max_length=16),
        ),
    ]
