# Generated by Django 4.1.7 on 2023-04-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_userreadings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userreadings',
            name='date_read',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
