# Generated by Django 4.2 on 2023-04-14 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='social_media_title',
            field=models.CharField(choices=[('FB', 'Facebook'), ('Instagram', 'Instagram'), ('TikTok', 'TikTok'), ('Twitter', 'Twitter'), ('Youtube', 'Youtube')], max_length=16),
        ),
    ]
